### ISSUE TITLE
Home Page Epic issue

### ISSUE THREAD

**Issue by alexelizaga** [alexelizaga/turborepo#3]
## Wiki
- [Home Page](https://github.com/alexelizaga/turborepo/wiki/Home-Page-Epic).

## Stories of the epic:
- [x] #4

## Testing
- [ ] Tested by UIX
- [ ] Tested by QA
- [ ] Tested by Analytics
